name: Bug report
description: File a bug report if MultiQC is breaking / not behaving in the way you expect
body:
  - type: textarea
    id: description
    attributes:
      label: Description of bug
      description: |
        A clear and concise description of what the bug is.
        **Please do note paste in the contents of example files** - upload them as a file in the field below.
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: MultiQC Error log
      description: Please paste your **full** MultiQC log.
      render: console

  - type: textarea
    id: error-file
    attributes:
      label: File that triggers the error
      description: |
        Please drag and drop (and upload to the GitHub issue) an input file that can be used to replicate the error.
        ***Please do not copy and paste log contents***, as important whitespace can change.
        If the file type is not allowed, please compress into a `.zip` file.
      placeholder: "[ Drag and drop an example file here to upload ]"

  - type: textarea
    id: command
    attributes:
      label: Command used to run MultiQC
      placeholder: eg. multiqc .
      render: bash

  - type: input
    id: version
    attributes:
      label: MultiQC Version
      placeholder: eg. MultiQC v1.10
